config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get 'import' => 'movies#import', :as => :import
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
    belongs_to :movie
    has_many :movie_locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :locations
end

app/models/director.rb
class Director < ApplicationRecord
    belongs_to :movie
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :country
    has_many :movie_locations
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :movie_actors
    has_many :movie_locations
    has_one :director
    has_many :locations
    has_many :reviews
end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
    belongs_to :movie
    belongs_to :actor
end

app/models/movie_location.rb
class MovieLocation < ApplicationRecord
    belongs_to :movie
    belongs_to :location
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
require 'csv'

class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    if(params[:search])
      @movies = Movie.includes(:reviews, :movie_actor).where('movie_actor.actor_id' => params[:search]).order("reviews.stars desc")
    else
      @movies = Movie.includes(:reviews).order("reviews.stars desc")
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    CSV.foreach(Rails.root.join("public", "movies.csv").to_s, headers: true) do |row|
      import_movie(row.to_h)
    end
    CSV.foreach(Rails.root.join("public", "reviews.csv").to_s, headers: true) do |row|
      import_review(row.to_h)
    end
  end


  private


    def import_movie(row)

      
      country_id = add_country(row["Country"])
      director_id = add_director(row["Director"])
      actor_id = add_actor(row["Actor"])
      location_id = add_location(row["Filming Location"], country_id)
      
      movie_name = row["Movie"]
      description = row["Description"]
      year = row["Year"]
      

      movie_id = Movie.find_or_create_by(name: movie_name, description: description, year: year, director_id: director_id)
      add_movie_actor(movie_id, actor_id)
      add_movie_location(movie_id, location_id)
    end

    def import_review(row)
      stars = row["Stars"]
      description = row["Review"]

      user_id = add_user(row["User"])
      movie_id = Movie.where(:name => row["Movie"]).first.id

      Review.find_or_create_by(movie_id: movie_id, user_id: user_id, description: description, stars: stars)
    end

    def add_country(country_name)
      Country.find_or_create_by(name: country_name).id
    end

    def add_director(director_name)
      name_split = director_name.split(' ', 2)
      Director.find_or_create_by(name: name_split[0], surname: name_split[1]).id
    end

    def add_actor(actor_name)
      name_split = actor_name.split(' ', 2)
      Actor.find_or_create_by(name: name_split[0], surname: name_split[1]).id
    end

    def add_user(user_name)
      name_split = user_name.split(' ', 2)
      User.find_or_create_by(name: name_split[0], surname: name_split[1]).id
    end

    def add_location(location, country_id)
      Location.find_or_create_by(name: location, country_id: country_id[1]).id
    end

    def add_movie_actor(movie_id, actor_id)
      MovieActor.find_or_create_by(movie_id: movie_id, actor_id: actor_id).id
    end

    def add_movie_location(movie_id, location_id)
      MovieLocation.find_or_create_by(movie_id: movie_id, location_id: location_id).id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :description, :year, :director_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mrdraper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :director_id %>
    <%= form.number_field :director_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/import.html.erb
<h1>Thank you for importing</h1>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>
<% form_tag movies_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Year</th>
      <th>Director</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= movie.year %></td>
        <td><%= movie.director_id %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Import', import_path %>
<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director_id %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>